services:
  api:
    build:
      context: .
      dockerfile: ./app/dockerfile
    volumes:
      - ./app:/app/app                # your code
      - ./data:/app/data              # persistent data directory
      - ./uploads:/app/uploads        # persistent uploads
      - ./requirements.txt:/app/requirements.txt:ro
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000      # API URL for browser access
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    depends_on:
      - api

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  frontend_node_modules:
