# docker-compose.yml
services:
  api:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    volumes:
      - ./app:/app/app
      - ./data/uploads:/app/data/uploads
      - ./requirements.txt:/app/requirements.txt:ro
    ports:
      - "8000:8000"
    command: >
      uvicorn app.main:app
        --reload
        --host 0.0.0.0
        --port 8000
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev
    depends_on:
      - api

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  frontend_node_modules:
